name: PrintScript CI

on:
  workflow_call:
    inputs:
      run_docker_compose:
        required: false
        type: boolean
        default: false

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        working-directory: './'

      - name: Docker compose tests run
        uses: cloudposse/github-action-docker-compose-test-run@0.2.0
        with:
          command: './gradlew build'
          file: 'docker-compose.yaml'
          registry: ghcr.io
          service: ''
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Spotless
        run: ./gradlew spotlessCheck
      - name: Check detekt
        run: ./gradlew detekt
      - name: Check kover
        run: ./gradlew koverVerify
      - name: Check test
        run: ./gradlew test
