name: PrintScript CI

on:
  - push
  - workflow_call

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Build with Gradle
        run: ./gradlew build
      - name: Check Spotless
        run: ./gradlew spotlessCheck
      - name: Check detekt
        run: ./gradlew detekt
      - name: Check kover
        run: ./gradlew koverVerify
      - name: Check test
        run: ./gradlew test