name: PrintScript CI

on:
  workflow_call:
    inputs:
      run_docker_compose:
        required: false
        type: boolean
        default: false

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Run Docker Compose
        if: ${{ inputs.run_docker_compose }}
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker-compose.yaml'

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Spotless
        run: ./gradlew spotlessCheck
      - name: Check detekt
        run: ./gradlew detekt
      - name: Check kover
        run: ./gradlew koverVerify
      - name: Check test
        run: ./gradlew test