name: "Update VM Docker"

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      is_dev:
        required: false
        type: boolean

jobs:
  vm_actions:
    name: Update VM Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.is_dev && secrets.ssh_host_dev || secrets.ssh_host }}
          username: ${{ inputs.is_dev && secrets.ssh_user_dev || secrets.ssh_user }}
          key: ${{ inputs.is_dev && secrets.ssh_key_dev || secrets.ssh_key }}
          port: 22
          script: |
            # Log in to Docker
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            
            # Pull the latest image
            docker pull ghcr.io/printscript8/${{ inputs.service_name }}:latest
            
            # Stop and remove any existing container
            docker stop ${{ inputs.service_name }} || true
            docker rm ${{ inputs.service_name }} || true
            
            # Determine if we are in dev or prod environment based on 'is_dev' input
            if [ ${{ inputs.is_dev }} = "true" ]; then
              echo "Running docker-compose.dev.yml"
              docker-compose -f docker-compose.dev.yml up -d
            elif [ ${{ inputs.is_dev }} = "false" ]; then
              echo "Running docker-compose.prod.yml"
              docker-compose -f docker-compose.prod.yml up -d
            else
              # Default case: Run the container directly
              echo "Running the container without docker-compose"
              docker run -d --name ${{ inputs.service_name }} -p 8080:8080 ghcr.io/printscript8/${{ inputs.service_name }}:latest
            fi